######################################################################
# Automatically generated by qmake (2.01a) ???? ?????? 6 19:46:16 2012
######################################################################

CONFIG += link_pkgconfig
TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .
PKGCONFIG = harfbuzz freetype2

# Input
SOURCES += hello.cc
