######################################################################
# Automatically generated by qmake (2.01a) ???? ?????? 6 19:46:16 2012
######################################################################

TEMPLATE = app
TARGET = hello
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += hello.cc
