######################################################################
# Automatically generated by qmake (2.01a) ???? ?????? 6 19:46:16 2012
######################################################################

CONFIG += link_pkgconfig
TEMPLATE = app
TARGET = QtHarfBuzzExample
DEPENDPATH += .
INCLUDEPATH += .
PKGCONFIG = harfbuzz freetype2 glib-2.0

# Input
SOURCES += QtHarfBuzzExample.cc
